// <auto-generated />
using System;
using CreativeCookies.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CreativeCookies.Data.Migrations
{
    [DbContext(typeof(PostsContext))]
    [Migration("20200506184513_seeding-local-db")]
    partial class seedinglocaldb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CreativeCookies.Domain.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9bb82c93-6705-497c-bf84-42876802dfd1"),
                            Content = "First seeded Post's content",
                            Description = "First seeded Post's description",
                            ImageUrl = "boy.jpg",
                            PublicationDate = new DateTime(2020, 5, 6, 20, 45, 12, 163, DateTimeKind.Local).AddTicks(4680),
                            Title = "First"
                        },
                        new
                        {
                            Id = new Guid("a874f8e9-35c1-4e2d-8cf3-6cee0db8ddab"),
                            Content = "And this is second post",
                            Description = "The description of second post",
                            ImageUrl = "girl.jpg",
                            PublicationDate = new DateTime(2020, 5, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Second"
                        },
                        new
                        {
                            Id = new Guid("04dab9fa-e74b-4e18-aee1-e1308cc16f12"),
                            Content = "And this is the third post",
                            Description = "It's description",
                            ImageUrl = "lorem-ipsum.jpg",
                            PublicationDate = new DateTime(2020, 5, 9, 8, 45, 12, 167, DateTimeKind.Local).AddTicks(6768),
                            Title = "Third"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
